"""update_asignaciones_horario

Revision ID: 3441631b932e
Revises: 4d0b1d5eec83
Create Date: 2026-05-03 00:25:04.604103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3441631b932e'
down_revision: Union[str, None] = '4d0b1d5eec83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('horario', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('asignaciones', sa.Column('minutos_por_hora_docente', sa.Integer(), nullable=False))
    op.drop_column('asignaciones', 'minutos_por_bloque')
    op.drop_column('asignaciones', 'dias_semana')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('dias_semana', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('asignaciones', sa.Column('minutos_por_bloque', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('asignaciones', 'minutos_por_hora_docente')
    op.drop_column('asignaciones', 'horario')
    # ### end Alembic commands ###
