"""initial_schema

Revision ID: 4d0b1d5eec83
Revises: 
Create Date: 2026-05-02 22:48:41.422057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d0b1d5eec83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_docentes_email'), 'docentes', ['email'], unique=True)
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.String(length=20), nullable=False),
    sa.Column('institucion', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_docente_id'), 'grupos', ['docente_id'], unique=False)
    op.create_table('asignaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('materia', sa.String(length=150), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('dias_semana', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('minutos_por_bloque', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('horas_semanales > 0', name='check_horas_positivas'),
    sa.CheckConstraint('minutos_por_bloque IN (45, 90)', name='check_minutos_validos'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_docente_id'), 'asignaciones', ['docente_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_grupo_id'), 'asignaciones', ['grupo_id'], unique=False)
    op.create_table('archivos_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('asignacion_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanio_bytes', sa.Integer(), nullable=True),
    sa.Column('subido_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_base_asignacion_id'), 'archivos_base', ['asignacion_id'], unique=False)
    op.create_index(op.f('ix_archivos_base_docente_id'), 'archivos_base', ['docente_id'], unique=False)
    op.create_table('desarrollo_diario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asignacion_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('texto_estructurado', sa.Text(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('revisado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desarrollo_diario_asignacion_id'), 'desarrollo_diario', ['asignacion_id'], unique=False)
    op.create_index(op.f('ix_desarrollo_diario_fecha'), 'desarrollo_diario', ['fecha'], unique=False)
    op.create_table('planificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asignacion_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas_docente', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planificaciones_asignacion_id'), 'planificaciones', ['asignacion_id'], unique=False)
    op.create_table('borradores_replanificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planificacion_id', sa.UUID(), nullable=False),
    sa.Column('contenido_propuesto', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('comentario_docente', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borradores_replanificacion_planificacion_id'), 'borradores_replanificacion', ['planificacion_id'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planificacion_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('clases_totales', sa.Integer(), nullable=False),
    sa.Column('clases_emergentes', sa.Integer(), nullable=False),
    sa.Column('porcentaje_emergentes', sa.Integer(), nullable=False),
    sa.Column('tiene_evaluacion', sa.Boolean(), nullable=False),
    sa.Column('tipo_evaluacion', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_planificacion_id'), 'unidades', ['planificacion_id'], unique=False)
    op.create_table('clases_planificadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unidad_id', sa.UUID(), nullable=False),
    sa.Column('numero_clase', sa.Integer(), nullable=False),
    sa.Column('fecha_estimada', sa.Date(), nullable=True),
    sa.Column('objetivo', sa.String(length=500), nullable=True),
    sa.Column('dinamica', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clases_planificadas_unidad_id'), 'clases_planificadas', ['unidad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clases_planificadas_unidad_id'), table_name='clases_planificadas')
    op.drop_table('clases_planificadas')
    op.drop_index(op.f('ix_unidades_planificacion_id'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_borradores_replanificacion_planificacion_id'), table_name='borradores_replanificacion')
    op.drop_table('borradores_replanificacion')
    op.drop_index(op.f('ix_planificaciones_asignacion_id'), table_name='planificaciones')
    op.drop_table('planificaciones')
    op.drop_index(op.f('ix_desarrollo_diario_fecha'), table_name='desarrollo_diario')
    op.drop_index(op.f('ix_desarrollo_diario_asignacion_id'), table_name='desarrollo_diario')
    op.drop_table('desarrollo_diario')
    op.drop_index(op.f('ix_archivos_base_docente_id'), table_name='archivos_base')
    op.drop_index(op.f('ix_archivos_base_asignacion_id'), table_name='archivos_base')
    op.drop_table('archivos_base')
    op.drop_index(op.f('ix_asignaciones_grupo_id'), table_name='asignaciones')
    op.drop_index(op.f('ix_asignaciones_docente_id'), table_name='asignaciones')
    op.drop_table('asignaciones')
    op.drop_index(op.f('ix_grupos_docente_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_index(op.f('ix_docentes_email'), table_name='docentes')
    op.drop_table('docentes')
    # ### end Alembic commands ###
